nodebb-forum:
# the image name should be updated to whatever name you use to tag your image
#  when built with the command: docker build -t n-bb/1 .
  image: n-bb/1
  volumes_from:
    - db
  links:
    - db
  ports:
    - 8080:4567
db:
  image: 'mongo:latest'
  ports:
    - '27017'
